name: build

permissions:
  contents: write

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: false
        default: ''
  schedule:
    - cron: '35 17 */14 * 5'  # Every second Friday at 18:35 CET

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux:
    runs-on: self-hosted
    timeout-minutes: 180
    container:
      image: ghcr.io/archlinux/archlinux:multilib-devel
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Prerequisities
      run: |
        sed -i 's/DownloadUser/#DownloadUser/g' /etc/pacman.conf
        pacman -Syu --noconfirm glibc-locales git strace patchelf curl wget base-devel autoconf cmake gtk3 dbus webkit2gtk-4.1  \
                                desktop-file-utils libglvnd glu nss-mdns libxcb libxshmfence libdrm egl-gbm vulkan-icd-loader \
                                openssl-1.1 xorg-server-xvfb gcc14 python github-cli ccache zsync libcanberra
        # Fix GMP compilation issues by symlinking GCC14 to /usr/bin/gcc
        rm /usr/bin/gcc
        ln -s /usr/bin/gcc-14 /usr/bin/gcc

    - name: Install iculess libxml2
      run: |
        LIBXML_URL="https://github.com/sarrchri/archlinux-pkgs-debloated/releases/download/continuous/libxml2-iculess-x86_64.pkg.tar.zst"
        wget --retry-connrefused --tries=30 "$LIBXML_URL" -O ./libxml2-iculess.pkg.tar.zst
        pacman -U --noconfirm ./libxml2-iculess.pkg.tar.zst
        rm -f ./libxml2-iculess.pkg.tar.zst

    - name: Install librsvg-mini
      run: |
        LIBRSVG_URL="https://github.com/sarrchri/archlinux-pkgs-debloated/releases/download/continuous/librsvg-mini-x86_64.pkg.tar.zst"
        wget --retry-connrefused --tries=30 "$LIBRSVG_URL" -O ./librsvg-mini.pkg.tar.zst
        pacman -U --noconfirm ./librsvg-mini.pkg.tar.zst
        rm -f ./librsvg-mini.pkg.tar.zst

    - name: Install gdk-pixbuf2-mini
      run: |
        GDK_PIXBUF2_URL="https://github.com/sarrchri/archlinux-pkgs-debloated/releases/download/continuous/gdk-pixbuf2-mini-x86_64.pkg.tar.zst"
        wget --retry-connrefused --tries=30 "$GDK_PIXBUF2_URL" -O ./gdk-pixbuf2-mini.pkg.tar.zst
        pacman -U --noconfirm ./gdk-pixbuf2-mini.pkg.tar.zst
        rm -f ./gdk-pixbuf2-mini.pkg.tar.zst

    - name: Clone PrusaSlicer repository
      run: |
        #git clone --recursive https://github.com/sarrchri/PrusaSlicer.git
        git clone https://gitlab.archlinux.org/archlinux/packaging/packages/prusa-slicer.git PrusaSlicer
        cd PrusaSlicer
        git fetch --tags
        TAG=${{ github.event.inputs.tag }}
        if [ -z "$TAG" ]; then
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        fi
        git checkout $TAG
        #CLEAN_TAG=$(echo $TAG|sed -e 's|version_||g')
        echo "VERSION=$TAG" >> $GITHUB_ENV

   # - name: ccache
   #   uses: hendrikmuhs/ccache-action@v1.2
   #   with:
   #     key: ${{ runner.os }}

   # - name: Determine dependency hash
   #   id: dephash
   #   run: |
   #        cd PrusaSlicer
   #        echo dephash=$(git rev-parse HEAD:deps) >> $GITHUB_OUTPUT

   # - name: Restore dependencies cache
   #   id: restore-dependencies-cache
   #   uses: actions/cache/restore@v4
   #   with:
   #     path: |
   #       PrusaSlicer/deps/build/destdir
   #     key: ${{ runner.os }}-${{ steps.dephash.outputs.dephash }}

   # - name: Populate download cache
   #   if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
   #   id: populate-download-cache
   #   uses: actions/cache@v4
   #   with:
   #     path: PrusaSlicer/deps/download
   #     key: ${{ runner.os }}-${{ github.run_id }}
   #     restore-keys: |
   #       ${{ runner.os }}

    #- name: Download GMP
    #  if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
    #  run: |
    #    mkdir -p PrusaSlicer/deps/download/GMP
    #    test -r PrusaSlicer/deps/download/GMP/gmp-6.2.1.tar.bz2 || curl -o PrusaSlicer/deps/download/GMP/gmp-6.2.1.tar.bz2 https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2

   # - name: Build dependencies
   #   if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
   #   run: |
   #     export CMAKE_POLICY_VERSION_MINIMUM=3.5
   #     export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
   #     cd PrusaSlicer/deps
   #     mkdir -p build
   #     cd build
   #     cmake .. -DDEP_WX_GTK3=ON -DDEP_DOWNLOAD_DIR=$(pwd)/../download
   #     make -j $(nproc)

   # - name: Save built dependencies
   #   id: save-dependencies-cache
   #   uses: actions/cache/save@v4
   #   with:
   #     path: |
   #       PrusaSlicer/deps/build/destdir
   #     key: ${{ steps.restore-dependencies-cache.outputs.cache-primary-key }}

   # - name: Build PrusaSlicer
   #   run: |
   #     export CMAKE_POLICY_VERSION_MINIMUM=3.5
   #     export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
   #     sed -i '/^set(SLIC3R_VERSION/s/")/+testing")/g' PrusaSlicer/version.inc
   #     mkdir -p PrusaSlicer/build
   #     cd PrusaSlicer/build
   #     cmake .. -DSLIC3R_STATIC=1 -DSLIC3R_GTK=3 -DSLIC3R_PCH=OFF -DCMAKE_PREFIX_PATH=$(pwd)/../deps/build/destdir/usr/local -DCMAKE_INSTALL_PREFIX=/usr
    #    make -j $(nproc)
    #    sudo make install
    #    find ../deps/build/destdir/usr/local

    - name: Bundle
      run: sh -ex ./bundle.sh

    - name: Release Artifacts
      uses: softprops/action-gh-release@v2
      with:
        name: "PrusaSlicer ${{ env.VERSION }}"
        tag_name: "prusaslicer_${{ env.VERSION }}"
        prerelease: false
        draft: false
        generate_release_notes: false
        make_latest: true
        files: |
            *.AppImage*